/**************************************************************************************************
								Additional Script for Gorion's Wraith
**************************************************************************************************/

IF
	True()
THEN
RESPONSE #100
	CutSceneId(Player1)
	CreateVisualEffectObject("SPFLESHS","QI#ZA25G")
	ActionOverride("QI#ZA25G",DestroySelf())
END
