/**************************************************************************************************
										The "Bully" 1
**************************************************************************************************/

/* Docks District Encounter */
IF
	InParty("QI#ZAK")
	See("QI#ZAK")	
	!StateCheck("QI#ZAK",CD_STATE_NOTVALID)
	CombatCounter(0)
	!See([ENEMY])
	Global("QI#ZakSalbreadQuest","GLOBAL",2)
	!Global("QI#ZakSalbreadQuestActive","GLOBAL",1)
THEN
RESPONSE #100
	SetGlobal("QI#ZakSalbreadQuest","GLOBAL",3)
END 

IF
	InParty("QI#ZAK")
	See("QI#ZAK")
	!StateCheck("QI#ZAK",CD_STATE_NOTVALID)
	Global("QI#ZakSalbreadQuest","GLOBAL",3)
THEN
RESPONSE #100
	Dialogue("QI#ZAK")
END 

/* Sewers District Final Encounter */
IF
	InParty("QI#ZAK")
	See("QI#ZAK")	
	!StateCheck("QI#ZAK",CD_STATE_NOTVALID)
	CombatCounter(0)
	!See([ENEMY])
	Global("QI#ZakSalbreadQuest","GLOBAL",5)
THEN
RESPONSE #100
	SetGlobal("QI#ZakSalbreadQuest","GLOBAL",6)
END

IF
	Global("QI#ZakSalbreadQuest","GLOBAL",6)
THEN
RESPONSE #100
	StartDialogueNoSet("QI#ZAK")
END 
