LOAD_TRA	~Zakrion/Zakrion_BG1/English/SETUP.tra~

	// Credits to the Sword and Fist mod
	ADD_KIT ~QI#DUELIST~
	~QI#DUELIST                 1           1           1           1           1 1           1           1~
	~QI#DUELIST 5 5 1 1 1 1 1 1 5 5 5 1 1 5 5 5 1 1 1 1 1 1 1 1 1 1 5 1 1 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~QI#DUELIST                 9      0      0      0       0      0~
	~QI#DUELIST                 0       0       0       0       0       0~
	~QI#DUELIST                 17      0      0       0       0      0~
	~QI#DUELIST                 15      0      0       0       0      0~
	~QI#DUELIST                 1       1       1       1       1       1       1 1       1~
	~QI#DUELIST                 0       1       1       1       1       0~
	~Zakrion/Zakrion_BG1/Duelist/QI#DUEL.2da~
	~~
	~0x00010000     2~
	~Fi0~
	~LEAT20 DART03,40 HELM07 BAG26 RING06 RING31 CLCK27 BOOT01 AMUL19 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW11 BOW19 XBOW06~
	SAY @1
	SAY @2
	SAY @3
	LAF fl#add_kit_ee 
		STR_VAR kit_name = ~QI#DUELIST~
	END

	COPY ~Zakrion/Zakrion_BG1/Items/QI#ZAKCU.itm~ ~override~
	SAY NAME1 @4
	SAY NAME2 @4
	SAY DESC @5

	APPEND ~STATE.IDS~ // adds custom IsValidForPartyDialogue state
		~0x80101FEF CD_STATE_NOTVALID~
	UNLESS ~CD_STATE_NOTVALID~
	
	// Portraits
	COPY ~Zakrion/Zakrion_BG1/Portraits/BGee/QI#ZakL.bmp~ ~override/QI#ZakL.bmp~
	COPY ~Zakrion/Zakrion_BG1/Portraits/BGee/QI#ZakM.bmp~ ~override/QI#ZakM.bmp~

	COPY ~Zakrion/Zakrion_BG1/Creatures/QI#ZAK.cre~ ~override/QI#ZAK.cre~
	WRITE_SHORT 0x246 (0x4000 + ~%QI#DUELIST%~)

	SAY NAME1 @6
	SAY NAME2 @6

	SAY BIO @7
	SAY MORALE @8
	SAY UNHAPPY_ANNOYED @9
	SAY UNHAPPY_SERIOUS @10
	SAY LEADER @11
	SAY TIRED @12
	SAY BORED @13
	SAY AREA_NIGHT @14
	SAY AREA_DAY @15
	SAY AREA_DUNGEON @16
	SAY AREA_CITY @16
	SAY AREA_FOREST @17
	SAY BATTLE_CRY1 @18
	SAY BATTLE_CRY2 @19
	SAY BATTLE_CRY3 @20
	SAY BATTLE_CRY4 @21
	SAY BATTLE_CRY5 @22
	SAY DAMAGE @23
	SAY DYING @24
	SAY HURT @25
	SAY SELECT_COMMON1 @26
	SAY SELECT_COMMON2 @27
	SAY SELECT_COMMON3 @28
	SAY SELECT_COMMON4 @29
	SAY SELECT_COMMON5 @30
	SAY SELECT_COMMON6 @31
	SAY SELECT_ACTION1 @32
	SAY SELECT_ACTION2 @33
	SAY SELECT_ACTION3 @34
	SAY SELECT_ACTION4 @35
	SAY SELECT_ACTION5 @36
	SAY SELECT_ACTION6 @37
	SAY SELECT_ACTION7 @38
	SAY CRITICAL_HIT @39
	SAY CRITICAL_MISS @40
	SAY TARGET_IMMUNE @41
	SAY INVENTORY_FULL @42
	SAY SELECT_RARE1 @43
	SAY SELECT_RARE2 @44
	SAY PICKED_POCKET @45
	SAY SPELL_DISRUPTED @46
	SAY HIDDEN_IN_SHADOWS @47
	SAY SET_A_TRAP @48

	COMPILE EVALUATE_BUFFER ~Zakrion/Zakrion_BG1/Dialogues/QI#ZAK.d~
		USING ~Zakrion/Zakrion_BG1/%LANGUAGE%/QI#ZAK.tra~
		
	COMPILE EVALUATE_BUFFER ~Zakrion/Zakrion_BG1/Dialogues/QI#ZAKP.d~
		USING ~Zakrion/Zakrion_BG1/%LANGUAGE%/QI#ZAKP.tra~
		
	COMPILE EVALUATE_BUFFER ~Zakrion/Zakrion_BG1/Dialogues/QI#ZAKJ.d~
		USING ~Zakrion/Zakrion_BG1/%LANGUAGE%/QI#ZAKJ.tra~
		
	COMPILE EVALUATE_BUFFER ~Zakrion/Zakrion_BG1/Dialogues/QI#ZAKB.d~
		USING ~Zakrion/Zakrion_BG1/%LANGUAGE%/QI#ZAKB.tra~

	COMPILE EVALUATE_BUFFER ~Zakrion/Zakrion_BG1/Scripts/QI#ZAKS.baf~
	COMPILE EVALUATE_BUFFER ~Zakrion/Zakrion_BG1/Scripts/QI#ZAKD.baf~

	ACTION_IF FILE_EXISTS_IN_GAME ~neera.dlg~ THEN BEGIN
	  COMPILE EVALUATE_BUFFER ~Zakrion/Zakrion_BG1/Dialogues/QI#ZAKEE.d~
		USING ~Zakrion/Zakrion_BG1/%LANGUAGE%/QI#ZAKEE.tra~
	END 

	 // Area Scripts
	 EXTEND_TOP ~AR3100.bcs~ ~Zakrion/Zakrion_BG1/Scripts/AR3100.baf~

LAF HANDLE_AUDIO END

APPEND ~pdialog.2da~
~QI#ZAK QI#ZAKP QI#ZAKJ QI#ZAKD~
UNLESS ~QI#ZAK~

APPEND ~interdia.2da~ 
~QI#ZAK QI#ZAKB~
UNLESS ~QI#ZAK~

